### Create Vendor
POST http://localhost:8080/api/v1/vendors
Content-Type: application/json

{
  "name": "Arihant Jewellers",
  "brandName": "Arihant",
  "email": "arihant@jewelcart.com",
  "phone": "9876543210",
  "gstIn": "22AAAAA0000A1Z5",
  "address": "Hyderabad, Telangana"
}

### Create Duplicate
POST http://localhost:8080/api/v1/vendors
Content-Type: application/json

{
  "name": "Arihant Copy",
  "brandName": "Arihant",
  "email": "arihant@jewelcart.com"
}

### Validation Failure
POST http://localhost:8080/api/v1/vendors
Content-Type: application/json

{
  "name": "",
  "brandName": ""
}

### Get All Vendors
GET http://localhost:8080/api/v1/vendors?page=0&size=10

### Get By ID Not Found
GET http://localhost:8080/api/v1/vendors/1